name: Anantlife.com
favicon: null
layout_spectrum: 0.7445433696266264
typography_spectrum: 0.98509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5e5f3'
    - '#140807'
    - '#c2b8b7'
    - '#53b4db'
    - '#b67353'
  brandStrength: 0.75
  lightness: 0.5865874700248241
  saturation: 0.6858940557576716
  rhythmicContrast: 0.2957154761534184
purpose: []
